spring:
  profiles:
    active:
    - dev-7001
---
spring:
  profiles: dev-7001
  application: 
    name: eureka-7001.com
server:
  port: 7001
  
security:
  basic:
    enabled: false   # 启用安全认证处理
  user:
    name: edmin     # 用户名
    password: mldnjava  # 密码
#security:
#  basic:
#    enabled: false   # 启用安全认证处理
#  user:
#    name: nyh     # 用户名
#    password: 123456  # 密码

eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7002.com:7002/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称

---
spring:
  profiles: dev-7002
  application: 
    name: eureka-7002.com
server:
  port: 7002
  
security:
  basic:
    enabled: false   # 启用安全认证处理
  user:
    name: edmin     # 用户名
    password: mldnjava  # 密码
#security:
#  basic:
#    enabled: false   # 启用安全认证处理
#  user:
#    name: nyh     # 用户名
#    password: 123456  # 密码

eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7003.com:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7002.com # 定义Eureka实例所在的主机名称

---
spring:
  profiles: dev-7003
  application: 
    name: eureka-7003.com
server:
  port: 7003
  
security:
  basic:
    enabled: false   # 启用安全认证处理
  user:
    name: edmin     # 用户名
    password: mldnjava  # 密码
#security:
#  basic:
#    enabled: false   # 启用安全认证处理
#  user:
#    name: nyh     # 用户名
#    password: 123456  # 密码

eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka,http://edmin:mldnjava@eureka-7002.com:7002/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7003.com # 定义Eureka实例所在的主机名称  
    
    
    
    
    
    